services:
  - type: web
    name: my-psychobot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
